meta_product_name: "Lucette Travel"
meta_title: "Lucette Travel, all your travel in one app"
meta_description: "Lucette travel, all your travel in one app. Spend less time organizing your trips and more time enjoying them!"
meta_image: "lucette-banner.png" # should exist in `app/assets/images/`

