meta_product_name: "Lucette Travel"
meta_title: "Lucette Travel, all your travel in one app"
meta_description: "Lucette travel, your travel companion which allows you to be organized during your trip and centralize pertinent information"
meta_image: "globe-europe.png" # should exist in `app/assets/images/`
