meta_product_name: "Lucette Travel"
meta_title: "Lucette Travel"
meta_description: "Lucette Travel, a travel helper which allows you to be organized and centralize relevant information during one's trip"
meta_image: "globe-europe.png" # should exist in `app/assets/images/`
